### ISSUE TITLE
Rename "Feature" to "Features" in test folder

### ISSUE THREAD

**Issue by driesvints** [laravelio/pastebin#23]
Should be plural. No idea why it's singular.

**Comment by MichaelDeBoey** [comment]
@driesvints Why should it be plural? All I see in the community is the folders with a singular name

**Comment by driesvints** [comment]
@MichaelDeBoey you're right! No idea why I thought it would be different.

**Comment by MichaelDeBoey** [comment]
Just looked at the issues I could maybe help with and found this one a bit odd that's why I was asking, just to be sure 🙂

Saw you also changed it for the rewrite of the portal (laravelio/portal#241) 🙂 
Keeping small things like this consistent through the whole community is something I see more when browsing more through interesting project 🙂
