### ISSUE TITLE
Docker configuration

### ISSUE THREAD

**Issue by codedge** [laravelio/pastebin#24]
Is there any plan to also provide Docker configuration additionally to VirtualBox?

I would send a PR, if you'd be ok with this.

**Comment by driesvints** [comment]
Heya, unfortunately not. Since this is an OS project for an app I'd like people to use the same environment when developing just like you'd do on any other web-app when working in large teams. Homestead comes closest to a Forge provisioned server so we'll stick with that.

Thanks for offering though! Feel free to ask any other question if you'd like 🙂
